<?php
/**
 * XMLRPC Proxy — handles raw XMLRPC pass-through with configurable trust.
 *
 * Modes:
 *   "off"                — reject all raw XMLRPC
 *   "passthrough_unsafe" — send all raw XMLRPC as trusted (dangerous)
 *   "sanitize"           — parse and sanitize known methods, send safe
 *                          payload as trusted; pass unknown methods as
 *                          untrusted (rtorrent whitelist decides)
 *
 * process() applies the policy and sends the result; decide() applies it and
 * returns the result, for a caller that owns its own connection to rtorrent.
 *
 * Dependencies of the process() convenience adapter:
 *   php/util.php    — FileUtil::toLog
 *   php/xmlrpc.php  — rXMLRPCRequest::send
 * Both shipped endpoints call decide() and own their transport/logging.
 * decide() has no external dependencies.
 */

class XMLRPCProxy
{
	// Methods that need trusted connections but can carry command
	// parameters. We rebuild these from scratch, keeping only safe params.
	//
	// Any unclassifiable, denied, or boundary-refused expression makes the
	// outer request locally terminal with no transport call.
	private static $sanitizeMethods = array(
		'load.normal', 'load.start', 'load.verbose', 'load.start_verbose',
		'load.raw', 'load.raw_start', 'load.raw_verbose', 'load.raw_start_verbose',
	);

	// Other sanitizeMethods are URI loads, checked against networkUri.
	private static $rawLoadMethods = array(
		'load.raw', 'load.raw_start', 'load.raw_verbose', 'load.raw_start_verbose',
	);

	private static $evaluatorDenies = array(
		'catch', 'branch', 'try', 'and', 'or', 'less', 'greater', 'equal', 'match',
	);

	private static $viewCarrierDenies = array(
		'view.filter', 'view.filter.temp', 'view.sort_new',
		'view.sort_current', 'view.event_added', 'view.event_removed',
	);

	// Exactly the URIs rtorrent does not treat as a local path:
	// is_network_uri() and is_magnet_uri() in core/download_factory.cc, which
	// use strncmp and are therefore case-sensitive. This has to agree with
	// them character for character — accepting a form rtorrent reads as a path
	// would be the hole this closes.
	private static $networkUri = '#^(?:http://|https://|ftp://|magnet:\?)#';

	// Multicalls carry commands in trailing positions, and the same rebuilding
	// applies. For multicalls all command slots, including filtered filters,
	// must be parsed and rebuilt; any unknown, denied, or unrebuildable command
	// causes terminal rejection of the entire outer call. A result slot is
	// matched against $safeParams and $safeGetters together, so a listing
	// request is rebuilt rather than refused; the filter slot is matched
	// against $safeParams alone. A small set of exact, read-only cat
	// expressions from bundled plugins is allowed in result slots verbatim.
	//
	// Refused outright in sanitize mode, whatever rtorrent would have made of
	// them. Matched as name prefixes, because these are families that differ
	// between versions — 0.9.8 has execute2 and schedule_remove2, 0.16.x has
	// execute.raw.bg and schedule.remove — and an exact list goes stale
	// silently, which for a refusal list is the wrong way to fail.
	//
	// This does not exist because rtorrent would allow them. It exists because
	// rtorrent only refuses them from 0.16.9, where UNTRUSTED_CONNECTION is
	// honoured; below that the header is read and ignored, so "forward it
	// untrusted" is a plain forward and this list is the only refusal there is.
	private static $denyPrefixes = array(
		'execute',                // and execute2, execute.capture, execute.raw.bg, ...
		'method.', 'system.method.', // current and pre-0.9.4 command mutation names
		'import', 'try_import',   // read a file of commands
		'schedule',               // and schedule2, schedule.remove, scheduler.*
		'log.',                   // log.execute, log.open_file, log.xmlrpc
		'network.scgi',           // re-open the listener somewhere else
		'session.path.set',
		'directory.default.set',
		'system.env',
		'system.shutdown',        // and .normal / .quick -- answered by the xmlrpc-c
		                          // registry, not rtorrent's command map, so rtorrent's
		                          // own untrusted gate never sees it
	);

	// The zero-argument read batch generated by the shipped Settings dialog on
	// 0.16.18-0.16.24. Two port getters are not marked safe by rTorrent itself,
	// so this *whole exact batch* needs trust; no subset or added command may
	// borrow it. rpc2.php does not load the plugin settings policy or JS; deriving
	// this grant from an expanding UI list would silently expand trusted RPC.
	// The 0.16.24 request is captured in XMLRPCProxyTest fixtures.
	private static $settingsReadMethods016 = array(
		'dht.statistics', 'pieces.hash.on_completion', 'network.bind_address', 'dht.port',
		'directory.default', 'throttle.global_down.max_rate', 'cat', 'cat',
		'cat', 'network.http.cacert', 'network.http.capath', 'network.proxy.http',
		'network.local_address', 'throttle.max_downloads.div', 'throttle.max_downloads.global', 'system.file.max_size',
		'pieces.memory.max', 'network.max_open_files', 'system.sockets.http.max_size', 'throttle.max_peers.normal',
		'throttle.max_peers.seed', 'throttle.max_uploads', 'throttle.max_uploads.global', 'throttle.min_peers.seed',
		'throttle.min_peers.normal', 'protocol.pex', 'cat', 'throttle.global_up.max_rate',
		'network.listen.port.random', 'network.listen.port.range', 'pieces.preload.min_size', 'pieces.preload.min_rate',
		'pieces.preload.type', 'network.proxy.global', 'network.receive_buffer.size', 'pieces.sync.always_safe',
		'network.scgi.dont_route', 'network.send_buffer.size', 'session.path', 'session.use_lock',
		'session.on_completion', 'system.file.split_size', 'system.file.split_suffix', 'pieces.sync.timeout_safe',
		'pieces.sync.timeout', 'trackers.numwant', 'trackers.use_udp', 'throttle.max_uploads.div',
		'system.sockets.max_size',
	);

	// Exact zero-argument WebUI reads captured in Chrome against rTorrent
	// 0.9.8 with httprpc disabled. The old daemon ignores the untrusted
	// SCGI flag, so none of these getters may be granted independently.
	private static $legacyPanelReadMethods098 = array(
		'settings read' => array(
			'dht.statistics', 'pieces.hash.on_completion', 'network.bind_address', 'dht.port',
			'directory.default', 'throttle.global_down.max_rate', 'cat', 'cat',
			'cat', 'network.http.cacert', 'network.http.capath', 'network.http.proxy_address',
			'network.local_address', 'throttle.max_downloads.div', 'throttle.max_downloads.global', 'system.file.max_size',
			'pieces.memory.max', 'network.max_open_files', 'network.http.max_open', 'throttle.max_peers.normal',
			'throttle.max_peers.seed', 'throttle.max_uploads', 'throttle.max_uploads.global', 'throttle.min_peers.seed',
			'throttle.min_peers.normal', 'protocol.pex', 'network.port_open', 'throttle.global_up.max_rate',
			'network.port_random', 'network.port_range', 'pieces.preload.min_size', 'pieces.preload.min_rate',
			'pieces.preload.type', 'network.proxy_address', 'network.receive_buffer.size', 'pieces.sync.always_safe',
			'network.scgi.dont_route', 'network.send_buffer.size', 'session.path', 'session.use_lock',
			'session.on_completion', 'system.file.split_size', 'system.file.split_suffix', 'pieces.sync.timeout_safe',
			'pieces.sync.timeout', 'trackers.numwant', 'trackers.use_udp', 'throttle.max_uploads.div',
			'network.max_open_sockets',
		),
		'panel totals read' => array(
			'throttle.global_up.total', 'throttle.global_down.total', 'throttle.global_up.max_rate', 'throttle.global_down.max_rate',
		),
		'panel sockets read' => array(
			'network.http.current_open', 'network.open_sockets',
		),
	);

	// Direct calls that match a listed shape are rebuilt and sent trusted.
	// An unmatched original elevation is refused locally. For names added to
	// serve checked WebUI batches, an unmatched direct call retains the older
	// untrusted route. A batch may send all-untrusted members without trust,
	// but mixed trust or a locally rejected member refuses the whole batch.
	//
	// The claim being made is per call, not per command: not "d.custom1.set is
	// safe" but "this call, naming one download by hash, with a value rtorrent
	// stores rather than parses, is within what the owner of this instance may
	// do". Measured, not assumed: a $-prefixed value arriving as an XMLRPC
	// parameter of these methods is stored verbatim and never executed.
	private static $elevate = array(
		'd.open'                        => array('hash'),
		'd.start'                       => array('hash'),
		'd.stop'                        => array('hash'),
		'd.close'                       => array('hash'),
		'd.custom1.set'                 => array('hash', 'text'),
		'd.custom2.set'                 => array('hash', 'text'),
		'd.custom3.set'                 => array('hash', 'text'),
		'd.custom4.set'                 => array('hash', 'text'),
		'd.custom5.set'                 => array('hash', 'text'),
		'd.custom.set'                  => array('hash', 'text', 'text'),
		'd.priority.set'                => array('hash', 'int'),
		'd.delete_tied'                 => array('hash'),
		'network.xmlrpc.size_limit.set' => array('empty', 'size'),
		// Checked WebUI batch members. Unmatched direct calls use rTorrent's gate.
		'f.prioritize_first.enable'     => array('file_target'),
		'f.prioritize_first.disable'    => array('file_target'),
		'f.prioritize_last.enable'      => array('file_target'),
		'f.prioritize_last.disable'     => array('file_target'),
		'd.update_priorities'           => array('hash'),
		'd.set_throttle_name'           => array('hash', 'scheduler_throttle'),
		'd.throttle_name.set'           => array('hash', 'scheduler_throttle'),
		'd.set_custom'                  => array('hash', 'scheduler_key', 'scheduler_state'),
		'view.set_visible'              => array('hash', 'ratio_view'),
		'view.set_not_visible'          => array('hash', 'ratio_view'),
		'd.views.push_back_unique'      => array('hash', 'ratio_view'),
		'd.views.remove'                => array('hash', 'ratio_view'),
	);

	// These names were added for checked WebUI batches. An unmatched direct
	// call must retain its pre-batch untrusted route (for example Sonarr's
	// d.views.push_back_unique(hash, sonarr_imported)). A homogeneous
	// untrusted batch stays untrusted; it cannot borrow another member's trust.
	// Do not list d.close: rTorrent 0.16.22 accepts surplus arguments on an
	// untrusted connection, closes the download, and skips event.download.closed.
	private static $batchElevations = array(
		'f.prioritize_first.enable', 'f.prioritize_first.disable',
		'f.prioritize_last.enable', 'f.prioritize_last.disable',
		'd.update_priorities', 'd.set_throttle_name', 'd.throttle_name.set',
		'd.set_custom', 'view.set_visible', 'view.set_not_visible',
		'd.views.push_back_unique', 'd.views.remove',
	);

	// Ceiling for network.xmlrpc.size_limit.set. A client raises it to add a
	// large torrent by file; without a bound it is also how a caller makes
	// rtorrent buffer as much as it likes.
	private static $sizeLimitMax = 16777216;
	// rTorrent v0.16.24 enforces 1024; older daemons need the same recovery floor.
	// A compact one-command XMLRPC request to raise the limit still fits.
	private static $sizeLimitMin = 1024;

	// These filesystem mutators have no confined argument contract here.
	// Refuse them locally even when an old daemon ignores the untrusted flag.
	private static $filesystemDenies = array(
		'd.create_link', 'd.delete_link', 'd.tied_to_file.set',
		'd.set_directory', 'd.set_directory_base',
		'create_link', 'delete_link', 'd.set_tied_to_file',
	);

	// rTorrent v0.9.8 redirects directory/session/scgi_* to denied commands.
	// Older daemons also register load_* and XMLRPC size-limit spellings; those
	// bypass the canonical load sanitizer and size ceiling if forwarded raw.
	// Old daemons ignore UNTRUSTED_CONNECTION, so refuse these names locally.
	private static $legacyDenies = array(
		'directory', 'session', 'scgi_port', 'scgi_local',
		'set_directory', 'set_session', 'get_scgi_dont_route', 'set_scgi_dont_route',
		'load', 'load_verbose', 'load_start', 'load_start_verbose',
		'load_raw', 'load_raw_start', 'load_raw_verbose',
		'set_xmlrpc_size_limit', 'xmlrpc_size_limit',
		'view_filter', 'view_sort_new', 'view_sort_current',
	);

	// Commands whose argument is a path rtorrent will write a download into.
	// Download::set_directory() / set_base_directory() select the download's root
	// directory: for a single-file torrent the data lands at <dir>/<info.name>,
	// and the caller wrote the torrent, so it names the file too. Unconfined,
	// that is an arbitrary file write as the user rtorrent runs as — which lands
	// in a PHP-executing docroot if one is reachable and writable.
	//
	// ruTorrent already confines these everywhere else: correctDirectory() holds
	// a directory inside $topDirectory for the panel, for addtorrent.php and for
	// httprpc's own settings branch. This path skipped it.
	//
	// Both spellings of the base-directory setter: rtorrent 0.16.22 registers
	// d.directory.base.set as the command and keeps d.directory_base.set as a
	// CMD_REDIRECT to it (src/main.cc, "widely used"), so a client may send
	// either and the boundary has to hold for either. A boundary that knew one
	// spelling was one a client could name its way around, once an operator
	// allowed the other.

	private static $directoryCommands = array(
		'd.directory.set', 'd.directory_base.set', 'd.directory.base.set',
	);

	// Commands whose argument list has more than one member, so a comma in
	// the text after '=' separates arguments rather than sitting inside one.
	// d.custom.if_z is the one read that takes two: the key and the value to
	// answer when the key is unset. Measured 2026-09-14 on 0.16.22:
	// d.custom.if_z=key,fallback split in two answers the fallback, and the
	// same text quoted as one argument faults "Missing default argument."
	private static $multiArgCommands = array(
		'd.custom.set' => 2,
		'd.custom.if_z' => 2,
	);

	// The shipped conf/xmlrpc_proxy.php calls defaultSafeParams() when available.
	// Keep the list here so an older persisted conf/ volume without that file
	// still gets a usable policy. Explicit installed lists remain overrides.
	//
	// An install without that file is not an install that decided to forbid
	// every command parameter, and treating it as one costs a client its
	// labels and its directories for a reason nothing on its side can see.
	// Measured on the live instance 2026-09-12: the container replaces conf/
	// with a volume seeded once, years before this file existed, so the list
	// reached the door only while a second copy of it lived in
	// plugins/httprpc/conf.php -- and #3251 removed that copy as duplication.
	// That removed duplicate explained why the fallback is kept in code.
	//
	// XMLRPCProxyPolicyParityTest checks the shipped file and policy overrides.
	// An explicit policy still wins outright: this is a default, not a floor.
	// A multicall result applies an allowed setter to every download in the
	// selected view;
	// d.delete_tied can unlink each download's tied .torrent. Both doors use
	// this same intentional view-wide write policy.
	private static $defaultSafeParams = array(
		'd.custom1.set', 'd.custom2.set', 'd.custom3.set', 'd.custom4.set',
		'd.custom5.set', 'd.custom.set',
		'd.directory.set', 'd.directory_base.set', 'd.directory.base.set',
		'd.priority.set', 'd.throttle_name.set',
		'd.views.push_back_unique', 'd.delete_tied',
		'd.open', 'd.close', 'd.start', 'd.stop',
		'f.set_create_queued', 'f.set_resize_queued',
	);

	public static function defaultSafeParams()
	{
		return self::$defaultSafeParams;
	}

	/**
	 * Normalize policy variables after the caller has loaded its own conf.
	 * Httprpc loads its plugin conf after the shared policy, so that override
	 * applies only there; rpc2 passes the shared policy without plugin conf.
	 * No file access happens here; both HTTP doors pass their current scope.
	 */
	public static function policySettings($vars)
	{
		$mode = isset($vars['XMLRPCProxy']) ? $vars['XMLRPCProxy'] : 'sanitize';
		$builtIn = !array_key_exists('XMLRPCProxySafeParams', $vars);
		$policyError = (!$builtIn && !is_array($vars['XMLRPCProxySafeParams']))
			? 'XMLRPCProxySafeParams must be an array; proxy disabled' : null;
		$safeParams = $builtIn ? self::defaultSafeParams() :
			($policyError === null ? $vars['XMLRPCProxySafeParams'] : array());
		return array(
			'mode' => $mode,
			'log' => isset($vars['XMLRPCProxyLog']) ? $vars['XMLRPCProxyLog'] : true,
			'safeParams' => $safeParams,
			'policyError' => $policyError,
			'allowLocalPaths' => isset($vars['XMLRPCProxyAllowLocalPaths'])
				? $vars['XMLRPCProxyAllowLocalPaths'] : false,
			'allowRootDirectory' => isset($vars['XMLRPCProxyAllowRootDirectory'])
				? $vars['XMLRPCProxyAllowRootDirectory'] : false,
			'logSuffix' => ($builtIn && $mode === 'sanitize') ? ' [built-in policy]' : '',
		);
	}

	/** Attach the built-in fallback hint to the outer decision, not each member. */
	public static function decisionLogLines($decision, $policy)
	{
		$lines = $decision['log'];
		if(count($lines) && !empty($policy['logSuffix']))
			$lines[0] .= $policy['logSuffix'];
		return $lines;
	}

	public static function safeGetters()
	{
		return self::$safeGetters;
	}

	// Commands a multicall may carry that only read.
	//
	// A multicall's result slots are how a client asks "tell me about every
	// download in this view", and $safeParams cannot answer for them: it is a
	// list of setters, so d.name= was never in it and never will be. With any
	// unrecognised command rejecting the whole outer call, that made every
	// ordinary listing request a refusal -- seen on the live instance
	// 2026-09-08, where a client asked for d.multicall2, was refused four
	// times, and fell back to asking about each download one command at a
	// time. Each of those single calls was forwarded, so the refusal bought
	// nothing; it only made the client slower.
	//
	// Rebuilt multicalls are sent trusted, so these readers may exceed the
	// daemon's single-call mark_safe surface. This is an intentional read-only
	// capability: httprpc mode=list already requests them over trusted RPC.
	//
	// Not configurable, and deliberately so. This file already keeps
	// $denyPrefixes, $elevate, $directoryCommands and $multiArgCommands in
	// code: what a caller may READ is a property of the proxy, the way those
	// are, and not the same decision as what it may WRITE. Putting it in
	// conf/ would also put it exactly where a container that replaces conf/
	// with a volume cannot see it -- which is the failure this fork has just
	// spent a release recovering from.
	//
	// Derived, not typed: every command rtorrent 0.16.22 registers under d.,
	// t., f. and p. that does not change state -- read off the daemon's own
	// registry as frozen in tests/php/RtorrentCompatibilityTest.php, minus the
	// names whose path says they write (set, erase, start, try_...), minus the
	// dispatchers and the call carrier (d.multicall2, f./p./t.multicall,
	// p.call_target -- they run commands rather than read anything, and a
	// nested d.multicall2 in a result slot walks the whole view once per row),
	// minus the two announce triggers, minus the two a multicall cannot carry
	// at all (d.custom.keys and d.custom.items take no argument, and nothing
	// after the '=' still hands the command one empty argument, so they fault
	// the whole listing however they are spelled; measured 2026-09-14 on
	// 0.16.22 over SCGI), plus the pre-0.9 spelling of each from the panel's
	// alias table (php/methods-0.9.4.php), because this list is matched
	// literally and a client may send either. Held to exactly that by
	// RtorrentCompatibilityTest::testXmlrpcProxyReadListIsTheDaemonsReadSurfaceInBothSpellings,
	// so a getter the list lacks is a failing test here rather than a refused
	// client -- for the daemon that snapshot was taken from; a name a later
	// release adds is not on the list until the snapshot is refreshed.
	//
	// Why the whole surface and not a hand-picked subset: a list built from
	// what the panel and one logged client happened to ask for refused
	// t.failed_counter, t.success_counter and d.load_date -- measured
	// 2026-09-14 against a live rtorrent 0.16.22 through this proxy -- and
	// each refusal takes a whole listing down, which is the failure this list
	// exists to end. Measured there too: the rebuilt shape, d.name="" and
	// d.custom="chk-state", is answered by the daemon exactly as d.name= is,
	// and a pre-0.9 spelling is forwarded and faults as unknown, which is the
	// daemon's answer to give.
	//
	// Read commands are rebuilt exactly as setters are, through
	// rebuildSafeLoadParam(), so an argument -- d.custom=chk-state names a
	// key -- is quoted, and a $-prefixed one, which rtorrent would call
	// rather than store, is refused. The three exact read-only cat expressions
	// from bundled plugins are handled separately in rebuildMulticallParam();
	// they do not authorize arbitrary cat expressions or add to this list.
	private static $safeGetters = array(
		// downloads
		'd.accepting_seeders', 'd.base_filename', 'd.base_filename.as_binary',
		'd.base_filename.base64', 'd.base_filename.base64_as_binary',
		'd.base_filename.hex', 'd.base_filename.or_as_binary',
		'd.base_filename.or_base64', 'd.base_path', 'd.base_path.as_binary',
		'd.base_path.base64', 'd.base_path.base64_as_binary', 'd.base_path.hex',
		'd.base_path.or_as_binary', 'd.base_path.or_base64',
		'd.base_path.realpath.or_empty', 'd.base_path.realpath.or_throw',
		'd.bitfield', 'd.bytes_done', 'd.chunk_size', 'd.chunks_hashed',
		'd.chunks_seen', 'd.complete', 'd.completed_bytes', 'd.completed_chunks',
		'd.connection_current', 'd.connection_leech', 'd.connection_seed',
		'd.creation_date', 'd.custom', 'd.custom.if_z', 'd.custom1', 'd.custom2',
		'd.custom3', 'd.custom4', 'd.custom5', 'd.custom_throw', 'd.directory',
		'd.directory.realpath.or_empty', 'd.directory.realpath.or_throw',
		'd.directory_base', 'd.down.choke_heuristics',
		'd.down.choke_heuristics.leech', 'd.down.choke_heuristics.seed',
		'd.down.rate', 'd.down.total', 'd.downloads_max', 'd.downloads_min',
		'd.free_diskspace', 'd.get_base_filename', 'd.get_base_path',
		'd.get_bitfield', 'd.get_bytes_done', 'd.get_chunk_size',
		'd.get_chunks_hashed', 'd.get_complete', 'd.get_completed_bytes',
		'd.get_completed_chunks', 'd.get_connection_current',
		'd.get_connection_leech', 'd.get_connection_seed', 'd.get_creation_date',
		'd.get_custom', 'd.get_custom1', 'd.get_custom2', 'd.get_custom3',
		'd.get_custom4', 'd.get_custom5', 'd.get_custom_throw', 'd.get_directory',
		'd.get_directory_base', 'd.get_down_rate', 'd.get_down_total',
		'd.get_free_diskspace', 'd.get_hash', 'd.get_hashing',
		'd.get_hashing_failed', 'd.get_ignore_commands', 'd.get_left_bytes',
		'd.get_loaded_file', 'd.get_local_id', 'd.get_local_id_html',
		'd.get_max_file_size', 'd.get_max_size_pex', 'd.get_message', 'd.get_mode',
		'd.get_name', 'd.get_peer_exchange', 'd.get_peers_accounted',
		'd.get_peers_complete', 'd.get_peers_connected', 'd.get_peers_max',
		'd.get_peers_min', 'd.get_peers_not_connected', 'd.get_priority',
		'd.get_priority_str', 'd.get_ratio', 'd.get_size_bytes',
		'd.get_size_chunks', 'd.get_size_files', 'd.get_size_pex',
		'd.get_skip_rate', 'd.get_skip_total', 'd.get_state',
		'd.get_state_changed', 'd.get_state_counter', 'd.get_throttle_name',
		'd.get_tied_to_file', 'd.get_timestamp_finished',
		'd.get_timestamp_started', 'd.get_tracker_focus', 'd.get_tracker_numwant',
		'd.get_tracker_size', 'd.get_up_rate', 'd.get_up_total',
		'd.get_uploads_max', 'd.group', 'd.group.name', 'd.hash', 'd.hashing',
		'd.hashing_failed', 'd.ignore_commands', 'd.incomplete', 'd.is_active',
		'd.is_hash_checked', 'd.is_hash_checking', 'd.is_meta', 'd.is_multi_file',
		'd.is_not_partially_done', 'd.is_open', 'd.is_partially_done',
		'd.is_pex_active', 'd.is_private', 'd.left_bytes', 'd.load_date',
		'd.loaded_file', 'd.loaded_file.realpath.or_empty',
		'd.loaded_file.realpath.or_throw', 'd.local_id', 'd.local_id_html',
		'd.max_file_size', 'd.max_size_pex', 'd.message', 'd.mode', 'd.name',
		'd.name.as_binary', 'd.name.base64', 'd.name.base64_as_binary',
		'd.name.hex', 'd.name.or_as_binary', 'd.name.or_base64', 'd.peer_exchange',
		'd.peers_accounted', 'd.peers_complete', 'd.peers_connected',
		'd.peers_max', 'd.peers_min', 'd.peers_not_connected', 'd.priority',
		'd.priority_str', 'd.ratio', 'd.size_bytes', 'd.size_chunks',
		'd.size_files', 'd.size_pex', 'd.skip.rate', 'd.skip.total', 'd.state',
		'd.state_changed', 'd.state_counter', 'd.throttle_name', 'd.tied_to_file',
		'd.tied_to_file.realpath.or_empty', 'd.tied_to_file.realpath.or_throw',
		'd.timestamp.finished', 'd.timestamp.finished.elapsed',
		'd.timestamp.finished.or_zero', 'd.timestamp.started',
		'd.timestamp.started.elapsed', 'd.timestamp.started.or_zero',
		'd.tracker.has_active', 'd.tracker.has_active_not_scrape',
		'd.tracker.has_usable', 'd.tracker_focus', 'd.tracker_numwant',
		'd.tracker_size', 'd.up.choke_heuristics', 'd.up.choke_heuristics.leech',
		'd.up.choke_heuristics.seed', 'd.up.rate', 'd.up.total', 'd.uploads_max',
		'd.uploads_min', 'd.views', 'd.views.has', 'd.wanted_chunks',
		// trackers
		't.activity_time_last', 't.activity_time_next', 't.can_scrape',
		't.failed_counter', 't.failed_time_last', 't.failed_time_next',
		't.get_group', 't.get_id', 't.get_min_interval', 't.get_normal_interval',
		't.get_scrape_complete', 't.get_scrape_downloaded',
		't.get_scrape_incomplete', 't.get_scrape_time_last', 't.get_type',
		't.get_url', 't.group', 't.id', 't.is_busy', 't.is_enabled',
		't.is_extra_tracker', 't.is_open', 't.is_scrapable', 't.is_usable',
		't.latest_event', 't.latest_new_peers', 't.latest_sum_peers',
		't.min_interval', 't.normal_interval', 't.scrape_complete',
		't.scrape_counter', 't.scrape_downloaded', 't.scrape_incomplete',
		't.scrape_time_last', 't.success_counter', 't.success_time_last',
		't.success_time_next', 't.type', 't.url',
		// files
		'f.completed_chunks', 'f.frozen_path', 'f.frozen_path.as_binary',
		'f.frozen_path.base64', 'f.frozen_path.hex', 'f.frozen_path.or_as_binary',
		'f.frozen_path.or_base64', 'f.frozen_path.realpath.or_empty',
		'f.frozen_path.realpath.or_throw', 'f.get_completed_chunks',
		'f.get_frozen_path', 'f.get_last_touched', 'f.get_match_depth_next',
		'f.get_match_depth_prev', 'f.get_offset', 'f.get_path',
		'f.get_path_components', 'f.get_path_depth', 'f.get_priority',
		'f.get_range_first', 'f.get_range_second', 'f.get_size_bytes',
		'f.get_size_chunks', 'f.is_create_queued', 'f.is_created', 'f.is_open',
		'f.is_resize_queued', 'f.last_touched', 'f.match_depth_next',
		'f.match_depth_prev', 'f.offset', 'f.path', 'f.path_components',
		'f.path_components.as_binary', 'f.path_components.base64',
		'f.path_components.base64_as_binary', 'f.path_components.hex',
		'f.path_components.or_as_binary', 'f.path_components.or_base64',
		'f.path_depth', 'f.prioritize_first', 'f.prioritize_last', 'f.priority',
		'f.range_first', 'f.range_second', 'f.size_bytes', 'f.size_chunks',
		// peers
		'p.address', 'p.banned', 'p.client_version', 'p.completed_percent',
		'p.down_rate', 'p.down_total', 'p.get_address', 'p.get_client_version',
		'p.get_completed_percent', 'p.get_down_rate', 'p.get_down_total',
		'p.get_id', 'p.get_id_html', 'p.get_options_str', 'p.get_peer_rate',
		'p.get_peer_total', 'p.get_port', 'p.get_up_rate', 'p.get_up_total',
		'p.id', 'p.id_html', 'p.is_encrypted', 'p.is_incoming', 'p.is_obfuscated',
		'p.is_preferred', 'p.is_snubbed', 'p.is_unwanted', 'p.options_str',
		'p.peer_rate', 'p.peer_total', 'p.port', 'p.snubbed', 'p.up_rate',
		'p.up_total',
	);

	private static $multicallMethods = array(
		'd.multicall', 'd.multicall2', 'd.multicall.filtered',
		't.multicall', 'f.multicall', 'p.multicall',
	);

	// A source-pinned ceiling for every expression we elevate. The table is
	// separate from permission lists: a name must be both allowed here and
	// registered natively by the stated daemon version.
	private static function nativeOnDaemon($name, $version)
	{
		// An omitted version gets the intersection of native methods across
		// supported daemons. It must never admit an rc alias on 0.9.8.
		if($version === null)
			$mask = 0x3FFFFFF;
		if($version === 0x0908)
			$mask = 1;
		elseif(is_int($version) && $version >= 0x1000 && $version <= 0x1018)
			$mask = 1 << (($version & 0xff) + 1);
		elseif($version !== null)
			return false;
		static $native = null;
		if($native === null)
			$native = require(__DIR__.'/xmlrpc_proxy_native.php');
		return isset($native[$name]) && (($native[$name] & $mask) === $mask);
	}

	/** One read-only probe, shared by both HTTP doors. */
	public static function daemonVersionProbe()
	{
		return '<?xml version="1.0"?><methodCall><methodName>system.client_version</methodName>'
			.'<params></params></methodCall>';
	}

	/** Parse the one read-only system.client_version reply into a supported version. */
	public static function daemonVersionFromReply($xml)
	{
		if(!is_string($xml) || $xml === '')
			return null;
		$doc = new DOMDocument();
		$prior = libxml_use_internal_errors(true);
		$loaded = $doc->loadXML($xml, LIBXML_NONET);
		libxml_clear_errors();
		libxml_use_internal_errors($prior);
		if(!$loaded)
			return null;
		$xp = new DOMXPath($doc);
		$nodes = $xp->query('/methodResponse/params/param/value/string');
		if($nodes === false || $nodes->length !== 1 ||
			$xp->query('/methodResponse/fault')->length !== 0)
			return null;
		return self::daemonVersionFromString($nodes->item(0)->textContent);
	}

	/** Parse a version string read directly from the daemon. */
	public static function daemonVersionFromString($value)
	{
		if(!is_string($value))
			return null;
		if(preg_match('/^0\.9\.8(?:[-+][A-Za-z0-9._-]+)?$/D', $value))
			return 0x0908;
		if(preg_match('/^0\.16\.(\d{1,2})(?:[-+][A-Za-z0-9._-]+)?$/D', $value, $m))
			return ((int)$m[1] <= 24) ? 0x1000 + (int)$m[1] : null;
		return null;
	}

	private static function oldDaemonDirectRead($name, $version)
	{
		return self::nativeOnDaemon($name, $version) &&
			(in_array($name, self::$safeGetters, true) ||
			in_array($name, array('system.client_version', 'system.api_version',
				'system.library_version', 'system.hostname', 'system.pid',
				'system.listMethods', 'view.list', 'directory.default'), true));
	}

	private static $log = true;

	private static function log($msg)
	{
		if(self::$log)
			FileUtil::toLog("xmlrpc-proxy: ".$msg);
	}

	private static $validTypes = array(
		'string', 'int', 'i4', 'i8', 'boolean', 'double',
		'dateTime.iso8601', 'base64', 'array', 'struct'
	);

	public static function normalizeMethodName($name)
	{
		if($name === null || $name === '')
			return null;
		$name = (string)$name;
		$clean = preg_replace('/[^A-Za-z0-9_.:-]/', '?', $name);
		if(strlen($clean) > 96)
			$clean = substr($clean, 0, 96);
		return $clean;
	}

	public static function formatLogMessage($msg)
	{
		$clean = preg_replace('/[\x00-\x1f\x7f]/', ' ', (string)$msg);
		if(strlen($clean) > 512)
			$clean = substr($clean, 0, 512);
		return $clean;
	}

	private static function isDeniedCommand($name)
	{
		if(in_array($name, self::$filesystemDenies, true) || in_array($name, self::$legacyDenies, true))
			return true;
		if(in_array($name, self::$evaluatorDenies, true))
			return true;
		if($name === 'p.call_target')
			return true;
		if(in_array($name, self::$viewCarrierDenies, true))
			return true;
		if(strncmp($name, 'directory.watch.', 16) === 0)
			return true;
		foreach(self::$denyPrefixes as $prefix)
		{
			if(strncmp($name, $prefix, strlen($prefix)) === 0)
				return true;
		}
		return false;
	}

	/**
	 * Return the first refused name in an rTorrent command expression.
	 *
	 * Multicall slots and httprpc cmd= values can contain nested commands
	 * introduced by a comma or $, so checking only the text before the first
	 * '=' misses a command rtorrent will execute. Keep the same deny policy as
	 * direct raw XMLRPC calls. '=' is deliberately not a separator: the value
	 * of d.custom=imported is an argument, not another command.
	 */
	public static function refusedCommandName($value)
	{
		$elements = preg_split('/[,\$\{\}()"\s]+/', (string)$value, -1, PREG_SPLIT_NO_EMPTY);
		if($elements === false)
			return null;
		foreach($elements as $element)
		{
			if(!preg_match('/^[A-Za-z0-9_.]+/', $element, $match))
				continue;
			if(self::isDirectDenied($match[0]))
				return $match[0];
		}
		return null;
	}

	/**
	 * Validate a cmd= value in the httprpc modes that execute it.
	 *
	 * The direct modes only add readers. Global settings/total extensions
	 * use exact legacy getter aliases shipped for this rtorrent version; a
	 * dynamically inserted get_* name proves nothing about side effects.
	 * prp uses the existing download reader registry. Multicall modes use the same slot
	 * rebuilder as the raw XMLRPC door, so arguments are quoted before sending.
	 * A null result is terminal for this HTTP request.
	 */
	public static function sanitizeHttprpcCommandParameter($raw, $mapped, $mode, $aliases = array(), $version = null)
	{
		if(!self::nativeOnDaemon(self::rawCommandName($mapped), $version))
			return null;
		if($mode === 'stg' || $mode === 'ttl' || $mode === 'prp')
		{
			if(self::refusedCommandName($raw) !== null
				|| self::refusedCommandName($mapped) !== null
				|| !preg_match('/^[A-Za-z][A-Za-z0-9_.]*$/D', $mapped)
				|| self::isDirectDenied($mapped))
				return null;
			if($mode === 'prp')
				return in_array($mapped, self::$safeGetters, true) ? $mapped : null;
			foreach($aliases as $legacy => $definition)
				if(strncmp($legacy, 'get_', 4) === 0
					&& isset($definition['name']) && $definition['name'] === $mapped
					&& ($raw === $legacy || $raw === $mapped))
					return $mapped;
			return null;
		}
		if($mode === 'trkall')
		{
			// trkall embeds each slot in an already quoted cat expression.
			// A rebuilt argument would introduce its own quotes into that
			// expression, so only plain zero-argument readers fit this form.
			if(!preg_match('/^([A-Za-z0-9_.]+)=$/D', $mapped, $match)
				|| self::isDirectDenied($match[1])
				|| !in_array($match[1], self::$safeGetters, true))
				return null;
			return $mapped;
		}
		if(in_array($mode, array('list', 'fls', 'prs', 'trk'), true))
		{
			// The rebuilder knows argument arity. A comma before a fallback
			// string is data in d.custom.if_z, but can introduce an executable
			// command in an arbitrary nested expression.
			$rebuilt = self::rebuildMulticallParam($mapped, self::$safeGetters, true, $version);
			return ($rebuilt === false) ? null : $rebuilt;
		}
		return null;
	}

	private static function isDirectDenied($name)
	{
		if(in_array($name, self::$directoryCommands, true))
			return true;
		return self::isDeniedCommand($name);
	}

	private static function isValidXmlUtf8String($str)
	{
		if(!is_string($str))
			return false;
		if(@preg_match('//u', $str) !== 1)
			return false;
		// Base64 URI text bypasses the input XML parser's character checks.
		// Valid UTF-8 alone does not exclude XML 1.0's U+FFFE and U+FFFF.
		if(preg_match('/[\x00-\x08\x0b\x0c\x0e-\x1f\x{fffe}\x{ffff}]/u', $str))
			return false;
		$escaped = htmlspecialchars($str, ENT_NOQUOTES, 'UTF-8');
		if($escaped === '' && $str !== '')
			return false;
		if(htmlspecialchars_decode($escaped, ENT_NOQUOTES) !== $str)
			return false;
		return true;
	}

	private static function hasNsOrAttrs($node, $xpath = null)
	{
		if($node->hasAttributes())
			return true;
		if($node->namespaceURI !== null && $node->namespaceURI !== '')
			return true;
		if($node->prefix !== null && $node->prefix !== '')
			return true;
		if($xpath !== null)
		{
			$nsList = $xpath->query('namespace::*[local-name() != "xml"]', $node);
			if($nsList->length > 0)
				return true;
		}
		return false;
	}

	private static function decodeCall($rawData)
	{
		if(!is_string($rawData) || $rawData === '')
			return array('ok' => false, 'error' => 'rejected (invalid XML)', 'method' => null);

		$prev = null;
		if(PHP_VERSION_ID < 80000 && function_exists('libxml_disable_entity_loader'))
			$prev = libxml_disable_entity_loader(true);
		$doc = new DOMDocument();
		$ok = @$doc->loadXML($rawData, LIBXML_NONET);
		if($prev !== null)
			libxml_disable_entity_loader($prev);

		if(!$ok)
			return array('ok' => false, 'error' => 'rejected (invalid XML)', 'method' => null);

		if($doc->doctype !== null)
			return array('ok' => false, 'error' => 'rejected (invalid XML)', 'method' => null);

		foreach($doc->childNodes as $docChild)
		{
			if($docChild->nodeType !== XML_ELEMENT_NODE)
				return array('ok' => false, 'error' => 'rejected (invalid XML)', 'method' => null);
		}

		$xpath = new DOMXPath($doc);
		$root = $doc->documentElement;
		if(!$root || $root->nodeName !== 'methodCall')
			return array('ok' => false, 'error' => 'rejected (invalid XML)', 'method' => null);

		if(self::hasNsOrAttrs($root, $xpath))
			return array('ok' => false, 'error' => 'rejected (invalid XML)', 'method' => null);

		$methodNode = null;
		$paramsNode = null;
		$elementCount = 0;

		foreach($root->childNodes as $child)
		{
			if($child->nodeType === XML_TEXT_NODE)
			{
				if(trim($child->nodeValue, " \t\r\n") !== '')
					return array('ok' => false, 'error' => 'rejected (invalid XML)', 'method' => null);
			}
			elseif($child->nodeType === XML_ELEMENT_NODE)
			{
				if(self::hasNsOrAttrs($child, $xpath))
					return array('ok' => false, 'error' => 'rejected (invalid XML)', 'method' => null);

				$elementCount++;
				if($elementCount === 1)
				{
					if($child->nodeName !== 'methodName')
						return array('ok' => false, 'error' => 'rejected (invalid XML)', 'method' => null);
					$methodNode = $child;
				}
				elseif($elementCount === 2)
				{
					if($child->nodeName !== 'params')
						return array('ok' => false, 'error' => 'rejected (invalid XML)', 'method' => null);
					$paramsNode = $child;
				}
				else
				{
					return array('ok' => false, 'error' => 'rejected (invalid XML)', 'method' => null);
				}
			}
			else
			{
				return array('ok' => false, 'error' => 'rejected (invalid XML)', 'method' => null);
			}
		}

		if($methodNode === null)
			return array('ok' => false, 'error' => 'rejected (invalid XML)', 'method' => null);

		if($methodNode->childNodes->length !== 1)
			return array('ok' => false, 'error' => 'rejected (invalid XML)', 'method' => null);
		$mnChild = $methodNode->childNodes->item(0);
		if($mnChild->nodeType !== XML_TEXT_NODE)
			return array('ok' => false, 'error' => 'rejected (invalid XML)', 'method' => null);
		$methodName = $mnChild->nodeValue;
		if($methodName === '' || trim($methodName, " \t\r\n") !== $methodName)
			return array('ok' => false, 'error' => 'rejected (invalid XML)', 'method' => null);

		$decodedParams = array();
		if($paramsNode !== null)
		{
			foreach($paramsNode->childNodes as $pChild)
			{
				if($pChild->nodeType === XML_TEXT_NODE || $pChild->nodeType === XML_CDATA_SECTION_NODE)
				{
					if(trim($pChild->nodeValue, " \t\r\n") !== '')
						return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);
				}
				elseif($pChild->nodeType === XML_ELEMENT_NODE)
				{
					if(self::hasNsOrAttrs($pChild, $xpath) || $pChild->nodeName !== 'param')
						return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);

					$paramRes = self::decodeParam($pChild, $methodName, $xpath);
					if(!$paramRes['ok'])
						return $paramRes;

					$decodedParams[] = $paramRes['param'];
				}
				else
				{
					return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);
				}
			}
		}

		return array(
			'ok' => true,
			'method' => $methodName,
			'params' => $decodedParams,
		);
	}

	private static function decodeParam($paramNode, $methodName, $xpath)
	{
		$valueNode = null;
		$valueCount = 0;
		foreach($paramNode->childNodes as $child)
		{
			if($child->nodeType === XML_TEXT_NODE || $child->nodeType === XML_CDATA_SECTION_NODE)
			{
				if(trim($child->nodeValue, " \t\r\n") !== '')
					return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);
			}
			elseif($child->nodeType === XML_ELEMENT_NODE)
			{
				if(self::hasNsOrAttrs($child, $xpath) || $child->nodeName !== 'value')
					return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);

				$valueCount++;
				if($valueCount > 1)
					return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);

				$valueNode = $child;
			}
			else
			{
				return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);
			}
		}

		if($valueCount !== 1 || $valueNode === null)
			return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);

		return self::decodeValue($valueNode, $methodName, $xpath);
	}

	private static function decodeValue($valueNode, $methodName, $xpath)
	{
		if(self::hasNsOrAttrs($valueNode, $xpath))
			return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);

		$elementChildren = array();
		$hasNonWhitespaceText = false;
		$rawText = '';

		foreach($valueNode->childNodes as $child)
		{
			if($child->nodeType === XML_TEXT_NODE || $child->nodeType === XML_CDATA_SECTION_NODE)
			{
				$rawText .= $child->nodeValue;
				if(trim($child->nodeValue, " \t\r\n") !== '')
					$hasNonWhitespaceText = true;
			}
			elseif($child->nodeType === XML_ELEMENT_NODE)
			{
				$elementChildren[] = $child;
			}
			else
			{
				return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);
			}
		}

		if(count($elementChildren) > 1)
			return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);

		if(count($elementChildren) === 1)
		{
			if($hasNonWhitespaceText)
				return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);

			$typeNode = $elementChildren[0];
			if(self::hasNsOrAttrs($typeNode, $xpath))
				return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);

			$tag = $typeNode->nodeName;
			if(in_array($tag, self::$validTypes, true))
			{
				if($tag === 'array')
				{
					$res = self::decodeArray($typeNode, $methodName, $xpath);
					if(!$res['ok'])
						return $res;
					return array('ok' => true, 'param' => array(
						'type' => 'array',
						'typeTag' => 'array',
						'value' => $res['data'],
					));
				}
				elseif($tag === 'struct')
				{
					$res = self::decodeStruct($typeNode, $methodName, $xpath);
					if(!$res['ok'])
						return $res;
					return array('ok' => true, 'param' => array(
						'type' => 'struct',
						'typeTag' => 'struct',
						'value' => $res['data'],
					));
				}
				else
				{
					$val = '';
					foreach($typeNode->childNodes as $scChild)
					{
						if($scChild->nodeType === XML_TEXT_NODE || $scChild->nodeType === XML_CDATA_SECTION_NODE)
						{
							$val .= $scChild->nodeValue;
						}
						else
						{
							return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);
						}
					}

					$type = ($tag === 'i4' || $tag === 'i8') ? 'int' : $tag;
					return array('ok' => true, 'param' => array(
						'type' => $type,
						'typeTag' => $tag,
						'value' => $val,
					));
				}
			}
			else
			{
				return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);
			}
		}

		return array('ok' => true, 'param' => array(
			'type' => 'string',
			'typeTag' => 'string',
			'value' => $rawText,
		));
	}

	private static function decodeArray($arrayNode, $methodName, $xpath)
	{
		$dataNode = null;
		$dataCount = 0;
		foreach($arrayNode->childNodes as $child)
		{
			if($child->nodeType === XML_TEXT_NODE || $child->nodeType === XML_CDATA_SECTION_NODE)
			{
				if(trim($child->nodeValue, " \t\r\n") !== '')
					return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);
			}
			elseif($child->nodeType === XML_ELEMENT_NODE)
			{
				if(self::hasNsOrAttrs($child, $xpath) || $child->nodeName !== 'data')
					return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);

				$dataCount++;
				if($dataCount > 1)
					return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);

				$dataNode = $child;
			}
			else
			{
				return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);
			}
		}

		if($dataCount !== 1 || $dataNode === null)
			return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);

		$items = array();
		foreach($dataNode->childNodes as $child)
		{
			if($child->nodeType === XML_TEXT_NODE || $child->nodeType === XML_CDATA_SECTION_NODE)
			{
				if(trim($child->nodeValue, " \t\r\n") !== '')
					return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);
			}
			elseif($child->nodeType === XML_ELEMENT_NODE)
			{
				if(self::hasNsOrAttrs($child, $xpath) || $child->nodeName !== 'value')
					return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);

				$valRes = self::decodeValue($child, $methodName, $xpath);
				if(!$valRes['ok'])
					return $valRes;

				$items[] = $valRes['param'];
			}
			else
			{
				return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);
			}
		}

		return array('ok' => true, 'data' => $items);
	}

	private static function decodeStruct($structNode, $methodName, $xpath)
	{
		$members = array();
		foreach($structNode->childNodes as $child)
		{
			if($child->nodeType === XML_TEXT_NODE || $child->nodeType === XML_CDATA_SECTION_NODE)
			{
				if(trim($child->nodeValue, " \t\r\n") !== '')
					return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);
			}
			elseif($child->nodeType === XML_ELEMENT_NODE)
			{
				if(self::hasNsOrAttrs($child, $xpath) || $child->nodeName !== 'member')
					return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);

				$memRes = self::decodeMember($child, $methodName, $xpath);
				if(!$memRes['ok'])
					return $memRes;

				$members[] = $memRes['data'];
			}
			else
			{
				return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);
			}
		}

		return array('ok' => true, 'data' => $members);
	}

	private static function decodeMember($memberNode, $methodName, $xpath)
	{
		$nameNode = null;
		$valNode = null;
		$elementCount = 0;

		foreach($memberNode->childNodes as $child)
		{
			if($child->nodeType === XML_TEXT_NODE)
			{
				if(trim($child->nodeValue, " \t\r\n") !== '')
					return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);
			}
			elseif($child->nodeType === XML_ELEMENT_NODE)
			{
				if(self::hasNsOrAttrs($child, $xpath))
					return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);

				$elementCount++;
				if($elementCount === 1)
				{
					if($child->nodeName !== 'name')
						return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);
					$nameNode = $child;
				}
				elseif($elementCount === 2)
				{
					if($child->nodeName !== 'value')
						return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);
					$valNode = $child;
				}
				else
				{
					return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);
				}
			}
			else
			{
				return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);
			}
		}

		if($nameNode === null || $valNode === null)
			return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);

		$nameText = '';
		foreach($nameNode->childNodes as $nc)
		{
			if($nc->nodeType === XML_TEXT_NODE || $nc->nodeType === XML_CDATA_SECTION_NODE)
			{
				$nameText .= $nc->nodeValue;
			}
			else
			{
				return array('ok' => false, 'error' => 'rejected (malformed XML envelope or structure)', 'method' => $methodName);
			}
		}

		$valRes = self::decodeValue($valNode, $methodName, $xpath);
		if(!$valRes['ok'])
			return $valRes;

		return array('ok' => true, 'data' => array(
			'name' => $nameText,
			'value' => $valRes['param'],
		));
	}

	private static function emitScalarValue($param)
	{
		if($param['type'] === 'array' || $param['type'] === 'struct'
			|| !in_array($param['typeTag'], self::$validTypes, true))
			return null;
		$tag = $param['typeTag'];
		return '<value><'.$tag.'>'.htmlspecialchars($param['value'], ENT_NOQUOTES, 'UTF-8')
			.'</'.$tag.'></value>';
	}

	private static function emitMethodCall($method, $paramsXml)
	{
		return '<?xml version="1.0" encoding="UTF-8"?>'."\n"
			.'<methodCall><methodName>'.htmlspecialchars($method, ENT_NOQUOTES, 'UTF-8')
			.'</methodName><params>'.$paramsXml.'</params></methodCall>';
	}

	private static function emitScalarValues($params, $wrapAsParams)
	{
		$xml = '';
		foreach($params as $param)
		{
			$value = self::emitScalarValue($param);
			if($value === null)
				return null;
			$xml .= $wrapAsParams ? '<param>'.$value.'</param>' : $value;
		}
		return $xml;
	}

	private static function emitCallFromScalars($method, $params)
	{
		$paramsXml = self::emitScalarValues($params, true);
		return $paramsXml === null ? null : self::emitMethodCall($method, $paramsXml);
	}

	private static function systemMulticallMember($member)
	{
		if($member['type'] !== 'struct')
			return null;
		$fields = array();
		foreach($member['value'] as $field)
		{
			$name = $field['name'];
			if(($name !== 'methodName' && $name !== 'params') || isset($fields[$name]))
				return null;
			$fields[$name] = $field['value'];
		}
		if(count($fields) !== 2 || $fields['methodName']['type'] !== 'string'
			|| $fields['params']['type'] !== 'array')
			return null;
		return array('method' => $fields['methodName']['value'],
			'params' => $fields['params']['value']);
	}

	private static function matchesExactReadBatch($members, $methods, $version, $requireNative)
	{
		if(count($members) !== count($methods))
			return false;
		foreach($members as $index => $rawMember)
		{
			$member = self::systemMulticallMember($rawMember);
			if($member === null || $member['method'] !== $methods[$index]
				|| count($member['params']) !== 0
				|| ($requireNative && !self::nativeOnDaemon($member['method'], $version)))
				return false;
		}
		return true;
	}

	private static function capturedReadBatch($members, $version)
	{
		if($version === 0x0908)
		{
			foreach(self::$legacyPanelReadMethods098 as $label => $methods)
				if(self::matchesExactReadBatch($members, $methods, $version, true))
					return $label;
		}
		// The captured 0.16 batch already covered a live socket getter absent
		// from the source-pinned native table; preserve that exact grant.
		elseif(is_int($version) && $version >= 0x1012 && $version <= 0x1018
			&& self::matchesExactReadBatch($members, self::$settingsReadMethods016, $version, false))
			return 'settings read';
		return false;
	}

	private static function memberDecisionLogs($index, $logs)
	{
		$prefixed = array();
		foreach($logs as $line)
			$prefixed[] = self::formatLogMessage('[slot '.($index + 1).'] '.$line);
		return $prefixed;
	}

	private static function rejectWithSlot($reason, $method, $index, $name, $note = '')
	{
		$detail = ' [slot '.($index + 1);
		if($name !== null)
			$detail .= ': '.$name;
		$outer = 'rejected ('.$reason.'): '.self::normalizeMethodName($method);
		return self::reject($outer.$detail.']'.$note, $method, $outer);
	}

	private static function rejectSystemMember($index, $method = null, $memberLogs = array(), $refused = null)
	{
		// A member has a literal method name; a command slot instead carries
		// "name=value" and must have its name extracted before formatting.
		$decision = self::rejectWithSlot('not allowed on this connection',
			'system.multicall', $index, self::normalizeMethodName($method));
		if($refused !== null)
			$decision['method'] = self::normalizeMethodName($refused);
		$decision['log'] = array_merge($decision['log'],
			self::memberDecisionLogs($index, $memberLogs));
		return $decision;
	}

	private static function rawCommandName($value)
	{
		if(!is_string($value))
			return null;
		$separator = strpos($value, '=');
		return trim(($separator === false) ? $value : substr($value, 0, $separator));
	}

	private static function commandName($value)
	{
		return self::normalizeMethodName(self::rawCommandName($value));
	}

	private static function rejectCommandSlot($reason, $method, $index, $value = null, $safeParams = null)
	{
		$name = self::commandName($value);
		$note = '';
		if($name === 'd.directory.base.set'
			&& in_array($method, self::$sanitizeMethods, true)
			&& is_array($safeParams)
			&& in_array('d.directory_base.set', $safeParams, true)
			&& !in_array('d.directory.base.set', $safeParams, true))
		{
			$note .= ' [policy lists d.directory_base.set but not d.directory.base.set;'
				.' add it to conf/xmlrpc_proxy.php or the httprpc policy override]';
		}
		if(($name === 'f.set_create_queued' || $name === 'f.set_resize_queued')
			&& is_array($safeParams) && !in_array($name, $safeParams, true))
		{
			$missing = array_diff(array('f.set_create_queued', 'f.set_resize_queued'), $safeParams);
			$note .= ' [add '.implode(' and ', $missing)
				.' to conf/xmlrpc_proxy.php or the httprpc policy override]';
		}
		$decision = self::rejectWithSlot($reason, $method, $index, $name, $note);
		$decision['offender'] = $name;
		return $decision;
	}

	private static function unmatchedElevation($methodName, $rawData, $version = null)
	{
		if($version === null || $version < 0x1009)
			return self::reject('rejected (arguments did not match allowed shape): '.
				self::normalizeMethodName($methodName), $methodName);
		if(in_array($methodName, self::$batchElevations, true))
			return self::forward($rawData, false,
				'untrusted: '.self::normalizeMethodName($methodName).' (shape not elevated)');
		return self::reject('rejected (arguments did not match allowed shape): '.
			self::normalizeMethodName($methodName), $methodName);
	}

	private static function emitArgumentFromDecoded($shape, $param, &$adjustedSize = null)
	{
		if($param['type'] === 'array' || $param['type'] === 'struct')
			return null;

		$val = $param['value'];

		switch($shape)
		{
			case 'hash':
				if($param['type'] !== 'string' || !preg_match('/^[0-9a-fA-F]{40}$/', $val))
					return null;
				return '<param><value><string>' . strtoupper($val) . '</string></value></param>';

			case 'file_target':
				if($param['type'] !== 'string' || !preg_match('/^[0-9a-fA-F]{40}:f(?:0|[1-9][0-9]*)$/', $val))
					return null;
				return '<param><value><string>' . strtoupper(substr($val, 0, 40))
					. substr($val, 40) . '</string></value></param>';

			case 'ratio_view':
				if($param['type'] !== 'string' || !preg_match('/^rat_(?:0|[1-9][0-9]{0,5})$/', $val))
					return null;
				return '<param><value><string>' . $val . '</string></value></param>';

			case 'scheduler_throttle':
				if($param['type'] !== 'string' || ($val !== '' && $val !== 'NULL'))
					return null;
				return '<param><value><string>' . $val . '</string></value></param>';

			case 'scheduler_key':
				if($param['type'] !== 'string' || $val !== 'sch_ignore')
					return null;
				return '<param><value><string>sch_ignore</string></value></param>';

			case 'scheduler_state':
				if($param['type'] !== 'string' || ($val !== '' && $val !== '1'))
					return null;
				return '<param><value><string>' . $val . '</string></value></param>';

			case 'empty':
				if($param['type'] !== 'string' || $val !== '')
					return null;
				return '<param><value><string></string></value></param>';

			case 'int':
				if($param['type'] !== 'int' && $param['type'] !== 'string')
					return null;
				if(!preg_match('/^(?:0|-?[1-9][0-9]{0,17})$/', $val))
					return null;
				return '<param><value><i8>' . $val . '</i8></value></param>';

			case 'size':
				if($param['type'] !== 'int' && $param['type'] !== 'string')
					return null;
				if(!preg_match('/^[1-9][0-9]{0,17}$/', $val))
					return null;
				if(strlen($val) > 8 || (int)$val > self::$sizeLimitMax)
					$size = self::$sizeLimitMax;
				else
					$size = (int)$val;
				$size = max(self::$sizeLimitMin, $size);
				if((int)$val !== $size)
					$adjustedSize = array('requested' => $val, 'sent' => $size);
				return '<param><value><i8>' . $size . '</i8></value></param>';

			case 'text':
				if($param['type'] !== 'string')
					return null;
				return '<param><value><string>'
					. htmlspecialchars($val, ENT_NOQUOTES, 'UTF-8')
					. '</string></value></param>';

			default:
				return null;
		}
	}

	/**
	 * Process a raw XMLRPC payload according to the configured mode.
	 *
	 * @param string $rawData     Raw XMLRPC XML from the client
	 * @param string $mode        "off", "passthrough_unsafe", or "sanitize"
	 * @param bool   $enableLog   Enable/disable logging
	 * @param array  $safeParams  Exact command names for load tails and multicall slots; results also allow safeGetters
	 *                            The empty API default rejects setter expressions and filtered multicalls.
	 *                            Endpoints without an explicit list pass defaultSafeParams(); this API does not.
	 * @param bool   $allowLocalPaths  Let a caller name a path on rtorrent's own
	 *                                 filesystem in load.start / load.normal
	 * @param array  $options     'directory' => array('root' => absolute path, optional 'resolve' => callable)
	 * @return string|null        SCGI response, or null on rejection
	 */
	public static function process($rawData, $mode = 'sanitize', $enableLog = true, $safeParams = array(), $allowLocalPaths = false, $options = array())
	{
		self::$log = $enableLog;

		$decision = self::decide($rawData, $mode, $safeParams, $allowLocalPaths, $options);

		foreach($decision['log'] as $line)
			self::log($line);

		if($decision['action'] !== 'send')
			return null;

		return rXMLRPCRequest::send($decision['payload'], $decision['trusted']);
	}

	/**
	 * Decide what to do with a raw XMLRPC payload, without acting on it.
	 *
	 * Same policy as process(), separated from the sending and the logging so
	 * that a caller holding its own connection to rtorrent can apply it —
	 * ruTorrent's SCGI plumbing needs the settings bootstrap, and an endpoint
	 * whose whole job is to filter one request should not have to carry that.
	 *
	 * @param string $rawData     Raw XMLRPC XML from the client
	 * @param string $mode        "off", "passthrough_unsafe", or "sanitize"
	 * @param array  $safeParams  Exact command names for load tails and multicall slots; results also allow safeGetters
	 *                            The empty API default rejects setter expressions and filtered multicalls.
	 *                            Endpoints without an explicit list pass defaultSafeParams(); this API does not.
	 * @param bool   $allowLocalPaths  Let a caller name a path on rtorrent's own
	 *                                 filesystem in load.start / load.normal.
	 *                                 Off by default: a remote client has no way
	 *                                 to know what is on that filesystem, and the
	 *                                 path it names becomes the download's tied
	 *                                 file, which d.delete_tied then unlinks.
	 * @param array  $options     'directory' => array('root' => absolute path, optional 'resolve' => callable)
	 * @return array  'action'  => "send" or "reject"
	 *                'payload' => the bytes to send, empty when rejecting
	 *                'trusted' => whether the connection carrying them may be trusted
	 *                'method'  => the command a refusal refused, null when forwarding
	 *                             or when the refusal names no single command
	 *                'log'     => what happened, in the order it happened
	 */
	public static function decide($rawData, $mode = 'sanitize', $safeParams = array(), $allowLocalPaths = false, $options = array())
	{
		$directory = isset($options['directory']) ? $options['directory'] : null;
		$version = array_key_exists('rtorrentVersion', $options)
			? $options['rtorrentVersion'] : null;

		if($mode === 'off' || ($mode !== 'passthrough_unsafe' && $mode !== 'sanitize'))
			return self::reject("rejected (proxy disabled)");

		if($mode === 'passthrough_unsafe')
			return self::forward($rawData, true, "passthrough (UNSAFE mode)");

		$decoded = self::decodeCall($rawData);
		if(!$decoded['ok'])
		{
			$method = isset($decoded['method']) ? $decoded['method'] : null;
			$logMsg = $decoded['error'];
			if($method !== null)
				$logMsg .= ': ' . self::normalizeMethodName($method);
			return self::reject($logMsg, $method, $decoded['error']);
		}

		$methodName = $decoded['method'];
		$params = $decoded['params'];
		if(array_key_exists('rtorrentVersion', $options) && $version !== 0x0908 &&
			(!is_int($version) || $version < 0x1000 || $version > 0x1018))
			return self::reject('rejected (unsupported or unreadable rTorrent version): '.
				self::normalizeMethodName($methodName), $methodName);

		if($methodName !== 'system.multicall'
			&& !self::nativeOnDaemon($methodName, $version)
			&& ($version === null || $version < 0x1009
				|| in_array($methodName, self::$sanitizeMethods, true)
				|| in_array($methodName, self::$multicallMethods, true)
				|| isset(self::$elevate[$methodName])))
			return self::reject('rejected (method is not native on this rTorrent version): '.
				self::normalizeMethodName($methodName), $methodName);

		if(self::isDirectDenied($methodName))
			return self::reject("rejected (not allowed on this connection): ".
				self::normalizeMethodName($methodName), $methodName);

		if($methodName === 'system.multicall')
		{
			if(count($params) !== 1 || $params[0]['type'] !== 'array'
				|| count($params[0]['value']) === 0)
				return self::reject("rejected (not allowed on this connection): system.multicall", $methodName);
			$capturedRead = self::capturedReadBatch($params[0]['value'], $version);
			$membersXml = '';
			$memberLogs = array();
			$untrustedMethods = array();
			$untrustedMethodsTruncated = false;
			$batchTrusted = null;
			foreach($params[0]['value'] as $index => $rawMember)
			{
				$member = self::systemMulticallMember($rawMember);
				if($member === null)
					return self::rejectSystemMember($index);
				$innerMethod = $member['method'];
				// Defense for future member shapes. Today's scalar-only parsing and
				// inner decide() also reject a nested carrier; the tests pin the
				// refusal, not this particular early exit.
				if($innerMethod === 'system.multicall')
					return self::rejectSystemMember($index, $innerMethod);
				$innerXml = self::emitCallFromScalars($innerMethod, $member['params']);
				if($innerXml === null)
					return self::rejectSystemMember($index, $innerMethod);
				$innerDecision = $capturedRead
					? self::forward($innerXml, true, 'trusted: '.$capturedRead)
					: self::decide($innerXml, $mode, $safeParams, $allowLocalPaths, $options);
				if($innerDecision['action'] !== 'send')
					return self::rejectSystemMember($index, $innerMethod, $innerDecision['log'],
						isset($innerDecision['offender']) ? $innerDecision['offender'] : $innerDecision['method']);
				if($batchTrusted !== null && $innerDecision['trusted'] !== $batchTrusted)
					return self::rejectSystemMember($index, $innerMethod, $innerDecision['log']);
				$batchTrusted = $innerDecision['trusted'];
				if(!$batchTrusted)
				{
					$name = self::normalizeMethodName($innerMethod);
					if(!in_array($name, $untrustedMethods, true))
					{
						if(count($untrustedMethods) < 3)
							$untrustedMethods[] = $name;
						else
							$untrustedMethodsTruncated = true;
					}
				}
				// Routine per-member decisions can turn one WebUI action into
				// thousands of lines. Keep only exceptional member warnings.
				foreach($innerDecision['log'] as $line)
					if(strpos($line, 'WARNING:') === 0)
						$memberLogs = array_merge($memberLogs,
							self::memberDecisionLogs($index, array($line)));
				// Fail closed if a future decision path changes the method or emits
				// a member value that this scalar-only carrier cannot encode.
				$checked = self::decodeCall($innerDecision['payload']);
				if(!$checked['ok'] || $checked['method'] !== $innerMethod)
					return self::rejectSystemMember($index, $innerMethod);
				$membersXml .= '<value><struct><member><name>methodName</name><value><string>'
					.htmlspecialchars($innerMethod, ENT_NOQUOTES, 'UTF-8')
					.'</string></value></member><member><name>params</name><value><array><data>';
				$valuesXml = self::emitScalarValues($checked['params'], false);
				if($valuesXml === null)
					return self::rejectSystemMember($index, $innerMethod);
				$membersXml .= $valuesXml;
				$membersXml .= '</data></array></value></member></struct></value>';
			}
			$canonicalXml = self::emitMethodCall('system.multicall',
				'<param><value><array><data>'.$membersXml.'</data></array></value></param>');
			$methods = $capturedRead ? ' ['.$capturedRead.']'
				: ($batchTrusted ? '' : ' [methods: '.implode(', ', $untrustedMethods)
					.($untrustedMethodsTruncated ? ', ...' : '').']');
			$decision = self::forward($canonicalXml, $batchTrusted,
				($batchTrusted ? 'trusted: ' : 'untrusted: ').'system.multicall ('
				.count($params[0]['value']).' members)'.$methods);
			$decision['log'] = array_merge($decision['log'], $memberLogs);
			return $decision;
		}

		if(in_array($methodName, self::$sanitizeMethods, true))
		{
			if(count($params) < 2)
				return self::reject("rejected (malformed load call): ".
					self::normalizeMethodName($methodName), $methodName);

			if($params[0]['type'] !== 'string')
				return self::reject("rejected (malformed load call): ".
					self::normalizeMethodName($methodName), $methodName);

			$targetVal = $params[0]['value'];
			$isRaw = in_array($methodName, self::$rawLoadMethods, true);
			$dataParam = $params[1];
			$localPath = null;

			if($isRaw)
			{
				if($dataParam['typeTag'] !== 'base64')
					return self::reject("rejected (malformed load call): ".
						self::normalizeMethodName($methodName), $methodName);

				$rawBytes = base64_decode($dataParam['value'], true);
				if($rawBytes === false)
					return self::reject("rejected (malformed load call): ".
						self::normalizeMethodName($methodName), $methodName);

				$canonicalDataXml = '<param><value><base64>'.base64_encode($rawBytes).'</base64></value></param>';
			}
			else
			{
				if($dataParam['type'] !== 'string' && $dataParam['typeTag'] !== 'base64')
					return self::reject("rejected (malformed load call): ".
						self::normalizeMethodName($methodName), $methodName);

				$uri = $dataParam['value'];
				if($dataParam['typeTag'] === 'base64')
				{
					$decodedUri = base64_decode($uri, true);
					if($decodedUri === false)
						return self::reject("rejected (malformed load call): ".
							self::normalizeMethodName($methodName), $methodName);
					$uri = $decodedUri;
				}

				if(!self::isValidXmlUtf8String($uri))
					return self::reject("rejected (malformed load call): ".
						self::normalizeMethodName($methodName), $methodName);

				if(!preg_match(self::$networkUri, $uri))
				{
					if(!$allowLocalPaths)
						return self::reject("rejected (load from a local path): ".
							self::normalizeMethodName($methodName), $methodName);
					$localPath = $uri;
				}

				$canonicalDataXml = '<param><value><string>'.htmlspecialchars($uri, ENT_NOQUOTES, 'UTF-8').'</string></value></param>';
			}

			$rebuiltCommands = array();

			for($i = 2; $i < count($params); $i++)
			{
				$cmdParam = $params[$i];
				if($cmdParam['type'] !== 'string')
					return self::rejectCommandSlot('malformed load call', $methodName, $i);

				$cmdVal = $cmdParam['value'];
				$rebuilt = self::rebuildSafeLoadParam($cmdVal, $safeParams, $directory, $version);
				if($rebuilt === false)
				{
					$reason = 'directory outside boundary';
					if(is_array($directory) && (!isset($directory['root']) || $directory['root'] === ''))
						$reason .= '; configure $topDirectory or $XMLRPCProxyAllowRootDirectory';
					return self::rejectCommandSlot($reason, $methodName, $i, $cmdVal, $safeParams);
				}
				if($rebuilt === null)
					return self::rejectCommandSlot('not allowed on this connection',
						$methodName, $i, $cmdVal, $safeParams);

				$rebuiltCommands[] = $rebuilt;
			}

			$paramsXml = '<param><value><string>'.htmlspecialchars($targetVal, ENT_NOQUOTES, 'UTF-8').'</string></value></param>'
				. $canonicalDataXml;
			foreach($rebuiltCommands as $rc)
				$paramsXml .= '<param><value><string>'.htmlspecialchars($rc, ENT_NOQUOTES, 'UTF-8').'</string></value></param>';
			$canonicalXml = self::emitMethodCall($methodName, $paramsXml);

			$totalKept = 2 + count($rebuiltCommands);
			$normMethod = self::normalizeMethodName($methodName);
			$paramDesc = "kept ".$totalKept." params";

			if($localPath !== null)
			{
				$logMsg = "WARNING: operator-enabled local path forwarded: ".$normMethod.
					"; trusted: ".$normMethod." (".$paramDesc.")";
			}
			else
			{
				$logMsg = "trusted: ".$normMethod." (".$paramDesc.")";
			}
			return self::forward($canonicalXml, true, $logMsg);
		}

		if(in_array($methodName, self::$multicallMethods, true))
		{
			$isFiltered = ($methodName === 'd.multicall.filtered');
			$isViewFirst = $methodName === 'd.multicall' && isset($params[1])
				&& $params[1]['type'] === 'string' && strpos($params[1]['value'], '=') !== false;
			$minParams = $isFiltered ? 4 : ($isViewFirst ? 2 : 3);
			if(count($params) < $minParams)
			{
				return self::reject("rejected (not allowed on this connection): " . self::normalizeMethodName($methodName), $methodName);
			}

			if($params[0]['type'] !== 'string')
				return self::rejectCommandSlot('not allowed on this connection', $methodName, 0);
			if($params[1]['type'] !== 'string')
				return self::rejectCommandSlot('not allowed on this connection', $methodName, 1);

			$targetVal = $params[0]['value'];
			$viewVal = $params[1]['value'];
			$resultCommands = array_merge($safeParams, self::$safeGetters);
			// Before 0.9.4 d.multicall is view-first: parameter 1 is already a
			// result command. Rebuild it too, so old UI listings work without an
			// executable escape. f./t./p.multicall use this slot only as data.
			if($isViewFirst)
			{
				$viewVal = self::rebuildMulticallParam($viewVal, $resultCommands, true, $version);
				if($viewVal === null || $viewVal === false)
					return self::rejectCommandSlot('not allowed on this connection', $methodName, 1, $params[1]['value']);
			}
			else if(strncmp($methodName, 'd.', 2) === 0 && strpos($viewVal, '=') !== false)
				return self::rejectCommandSlot('ambiguous multicall view', $methodName, 1, $viewVal);

			$filterVal = null;
			$resultStartIndex = 2;
			if($isFiltered)
			{
				if($params[2]['type'] !== 'string')
					return self::rejectCommandSlot('not allowed on this connection', $methodName, 2);
				$rawFilter = $params[2]['value'];
				$rebuiltFilter = self::rebuildMulticallParam($rawFilter, $safeParams, false, $version);
				if($rebuiltFilter === null || $rebuiltFilter === false)
				{
					return self::rejectCommandSlot('not allowed on this connection', $methodName, 2, $rawFilter);
				}
				$filterVal = $rebuiltFilter;
				$resultStartIndex = 3;
			}

			// Result slots may name a reader as well as a setter. The filter
			// slot of d.multicall.filtered above keeps the setter-only rule it
			// had before the read list existed: widening it is a separate
			// decision that nobody has asked for, not a property of filters --
			// rtorrent evaluates a filter command per download exactly as it
			// evaluates a result command.
			$rebuiltResults = array();
			for($i = $resultStartIndex; $i < count($params); $i++)
			{
				if($params[$i]['type'] !== 'string')
					return self::rejectCommandSlot('not allowed on this connection', $methodName, $i);

				$cmd = $params[$i]['value'];
				$rebuilt = self::rebuildMulticallParam($cmd, $resultCommands, true, $version);
				if($rebuilt === null || $rebuilt === false)
				{
					return self::rejectCommandSlot('not allowed on this connection', $methodName, $i, $cmd, $safeParams);
				}
				$rebuiltResults[] = $rebuilt;
			}

			$paramsXml = '<param><value><string>' . htmlspecialchars($targetVal, ENT_NOQUOTES, 'UTF-8') . '</string></value></param>'
				. '<param><value><string>' . htmlspecialchars($viewVal, ENT_NOQUOTES, 'UTF-8') . '</string></value></param>';
			if($isFiltered)
				$paramsXml .= '<param><value><string>' . htmlspecialchars($filterVal, ENT_NOQUOTES, 'UTF-8') . '</string></value></param>';
			foreach($rebuiltResults as $rr)
				$paramsXml .= '<param><value><string>' . htmlspecialchars($rr, ENT_NOQUOTES, 'UTF-8') . '</string></value></param>';
			$canonicalXml = self::emitMethodCall($methodName, $paramsXml);

			$totalParams = count($params);
			return self::forward($canonicalXml, true, "trusted: " . self::normalizeMethodName($methodName) . " (" . $totalParams . " params)");
		}

		if(isset(self::$elevate[$methodName]))
		{
			$shapes = self::$elevate[$methodName];
			if(count($params) !== count($shapes))
				return self::unmatchedElevation($methodName, $rawData, $version);

			$canonicalParams = array();
			$adjustedSize = null;
			for($i = 0; $i < count($shapes); $i++)
			{
				$shape = $shapes[$i];
				$param = $params[$i];
				$emitted = self::emitArgumentFromDecoded($shape, $param, $adjustedSize);
				if($emitted === null)
					return self::unmatchedElevation($methodName, $rawData, $version);
				$canonicalParams[] = $emitted;
			}

			$canonicalXml = self::emitMethodCall($methodName, implode('', $canonicalParams));

			$decision = self::forward($canonicalXml, true,
				"trusted: " . self::normalizeMethodName($methodName) . " (elevated)");
			if($adjustedSize !== null)
				$decision['log'][] = 'WARNING: network.xmlrpc.size_limit.set requested '
					.$adjustedSize['requested'].', sent '.$adjustedSize['sent'];
			return $decision;
		}

		// Old rTorrent ignores UNTRUSTED_CONNECTION. A direct fallback must
		// therefore be a source-pinned native reader, never an rc alias.
		if(($version === null || $version < 0x1009)
			&& !self::oldDaemonDirectRead($methodName, $version))
			return self::reject('rejected (direct command is not an approved native read): '.
				self::normalizeMethodName($methodName), $methodName);
		return self::forward($rawData, false, "untrusted: " . self::normalizeMethodName($methodName));
	}

	/**
	 * May a download be written into this path?
	 *
	 * $directory is the policy: array('root' => <absolute path>, 'resolve' =>
	 * <callable|null>). Without one, no — a caller naming a write target has to
	 * be answered from a stated boundary, and "none was stated" is not a boundary.
	 *
	 * The value normally does not exist yet, so realpath() on it returns false
	 * and cannot be the check. A lexical check alone is not enough either: one
	 * symlink inside the tree, which the customer can create, points anywhere.
	 * So the lexical check runs first and the resolver is then asked about the
	 * deepest part that does exist.
	 */
	private static function directoryIsAllowed($path, $directory)
	{
		if(!is_array($directory) || !isset($directory['root']))
			return false;
		$root = self::normalisePath($directory['root']);
		if(($root === null) || ($root === ''))
			return false;

		$path = self::normalisePath($path);
		if($path === null)
			return false;
		if(!self::isInside($path, $root))
			return false;

		if(isset($directory['resolve']) && is_callable($directory['resolve']))
		{
			$real = call_user_func($directory['resolve'], $path);
			$realRoot = call_user_func($directory['resolve'], $root);
			// A resolver that cannot answer for either side leaves the question
			// open, and an open question about a write target is a no.
			if(!is_string($real) || !is_string($realRoot) || ($real === '') || ($realRoot === ''))
				return false;
			if(!self::isInside($real, $realRoot))
				return false;
		}

		return true;
	}

	/**
	 * Collapse '.', '..' and repeated separators without touching the
	 * filesystem. Returns null for anything that is not an absolute path,
	 * including one that climbs above '/'.
	 */
	private static function normalisePath($path)
	{
		$path = trim((string)$path);
		if(($path === '') || ($path[0] !== '/'))
			return null;
		$out = array();
		foreach(explode('/', $path) as $part)
		{
			if(($part === '') || ($part === '.'))
				continue;
			if($part === '..')
			{
				if(count($out) === 0)
					return null;
				array_pop($out);
				continue;
			}
			$out[] = $part;
		}
		return '/'.implode('/', $out);
	}

	/**
	 * Is $path the root itself or something under it? Compared with the
	 * separator attached, so /torrents1x is not inside /torrents1.
	 */
	private static function isInside($path, $root)
	{
		if($root === '/')
			return true;
		return ($path === $root) || (strpos($path, rtrim($root, '/').'/') === 0);
	}

	private static function forward($payload, $trusted, $line)
	{
		return array('action' => 'send', 'payload' => $payload,
			'trusted' => $trusted, 'method' => null, 'log' => array(self::formatLogMessage($line)));
	}

	/**
	 * A refusal. $method names the command that was refused, when the refusal
	 * has one to name — a door renders it back to the caller so the client is
	 * told what it may not do, instead of being left to guess.
	 */
	private static function reject($line, $method = null, $error = null)
	{
		return array(
			'action' => 'reject',
			'payload' => '',
			'trusted' => false,
			'method' => self::normalizeMethodName($method),
			'log' => array(self::formatLogMessage($line)),
			'error' => ($error !== null) ? $error : $line,
		);
	}

	/**
	 * The sentence both doors show when this filter refuses a call. It names the
	 * command so a refusal reads the same at either door, and it says this
	 * server refused the call rather than blaming rtorrent for an outage that
	 * did not happen -- rtorrent never saw it.
	 */
	public static function rejectionMessage($method)
	{
		$cleanMethod = self::normalizeMethodName($method);
		return (($cleanMethod !== null) && ($cleanMethod !== ''))
			? "The command '".$cleanMethod."' was rejected by this server."
			: "This XMLRPC call was rejected by this server.";
	}

	/**
	 * The same sentence wrapped in the XMLRPC fault a door returns: faultCode
	 * -501, matching what rpc2.php answers for the same refusals.
	 */
	public static function rejectionFault($method)
	{
		return self::faultXml(self::rejectionMessage($method));
	}

	/** XMLRPC -501 fault body shared with rpc2.php's other HTTP refusals. */
	public static function faultXml($faultString)
	{
		return '<?xml version="1.0" encoding="UTF-8"?>'."\n"
			.'<methodResponse><fault><value><struct>'
			.'<member><name>faultCode</name><value><i4>-501</i4></value></member>'
			.'<member><name>faultString</name><value><string>'
			.htmlspecialchars($faultString, ENT_NOQUOTES, 'UTF-8')
			.'</string></value></member>'
			.'</struct></value></fault></methodResponse>';
	}

	/**
	 * Split command arguments up to the command's known arity. Before the final
	 * argument, commas separate values the way rtorrent expects; the final one
	 * keeps raw commas so existing labels and paths remain one value. A
	 * double-quoted string is one argument even when it contains commas.
	 * Unquoted arguments are trimmed; quoted ones are not. An unclosed quote,
	 * or text after a quoted argument that is not a comma, is malformed and
	 * returns null. The production policy treats that result as a terminal
	 * rejection of the complete outer request without a transport call.
	 *
	 * Clients such as cross-seed quote every value (d.custom1.set="cross-seed").
	 * Splitting on ',' first would cut inside those quotes; dropping them left
	 * torrents unlabeled and in the default directory. Unquoting here, then
	 * re-quoting in rebuildSafeLoadParam, keeps the value as one argument.
	 */
	private static function splitLoadArguments($value, $maxArguments)
	{
		if(!is_int($maxArguments) || $maxArguments < 1)
			return null;

		$arguments = array();
		$len = strlen($value);
		$i = 0;
		while(true)
		{
			while($i < $len && ($value[$i] === ' ' || $value[$i] === "\t"))
				$i++;
			$isLastArgument = (count($arguments) + 1 >= $maxArguments);

			if($i < $len && $value[$i] === '"')
			{
				$i++;
				$argument = '';
				$closed = false;
				while($i < $len)
				{
					$c = $value[$i];
					if($c === '\\' && $i + 1 < $len)
					{
						$argument .= $value[$i + 1];
						$i += 2;
						continue;
					}
					if($c === '"')
					{
						$closed = true;
						$i++;
						break;
					}
					$argument .= $c;
					$i++;
				}
				if(!$closed)
					return null;
				$arguments[] = $argument;
			}
			else
			{
				// Only one escape changes where an argument ends: rtorrent reads
				// '\\,' as a comma inside the value rather than a separator
				// (parse_string, src/rpc/parse.cc), so splitting on every comma
				// cut such a value in two and delivered a second argument the
				// client never sent.
				//
				// Its other escapes are deliberately left alone. rtorrent would
				// read '\\' as an escape everywhere, which turns C:\\downloads
				// into C:downloads -- but this side re-quotes the value, so the
				// backslash reaches rtorrent intact, and clients have been
				// sending paths and labels through here on that basis. Matching
				// rtorrent exactly would eat those backslashes.
				$argument = '';
				$keep = 0;
				while($i < $len)
				{
					$c = $value[$i];
					if($c === ',' && !$isLastArgument)
						break;
					if(($c === '\\') && ($i + 1 < $len) && ($value[$i + 1] === ','))
					{
						$argument .= ',';
						$i += 2;
						$keep = strlen($argument);
						continue;
					}
					$argument .= $c;
					$i++;
					// Trailing whitespace is trimmed as rtorrent trims it.
					if(($c !== ' ') && ($c !== "\t"))
						$keep = strlen($argument);
				}
				$arguments[] = substr($argument, 0, $keep);
			}

			while($i < $len && ($value[$i] === ' ' || $value[$i] === "\t"))
				$i++;
			if($i < $len)
			{
				if($value[$i] !== ',')
					return null;
				if(count($arguments) >= $maxArguments)
					return null;
				$i++;
			}
			else
				break;
		}
		return $arguments;
	}

	// Both filter and result slots execute per download and refuse directory
	// setters outright. The directory boundary is checked only for load.* tails.
	private static function rebuildMulticallParam($value, $allowed, $resultSlot = false, $version = null)
	{
		// These exact read expressions are shipped by ratio and
		// show_peers_like_wtorrent. The two tracker forms returned 0#0# in a
		// local rTorrent 0.16.22 lab with an actual test download. Do not allow
		// a general cat evaluator or client-selected nested commands.
		if($resultSlot && ($value === 'cat=$d.views='
			|| $value === 'cat="$t.multicall=d.hash=,t.scrape_complete=,cat={#}"'
			|| $value === 'cat="$t.multicall=d.hash=,t.scrape_incomplete=,cat={#}"'))
			return (self::nativeOnDaemon('cat', $version)
				&& self::nativeOnDaemon('d.views', $version)
				&& self::nativeOnDaemon('d.hash', $version)
				&& self::nativeOnDaemon('t.multicall', $version)
				&& self::nativeOnDaemon('t.scrape_complete', $version)
				&& self::nativeOnDaemon('t.scrape_incomplete', $version)) ? $value : null;
		$name = self::rawCommandName($value);
		if($name === null || self::isDirectDenied($name))
			return null;
		return self::rebuildSafeLoadParam($value, $allowed, null, $version);
	}

	/**
	 * Rebuild one command parameter. A null or false result makes the production
	 * policy reject the complete outer request without a transport call.
	 *
	 * A parameter is not a single command: rtorrent ends a command at ';' or a
	 * newline and calls a parenthesised (command,args) found in a value, so a
	 * string that merely begins with an allowed command can carry others. The
	 * command name is therefore compared for equality, and each argument is
	 * quoted so that whatever it contains stays an argument.
	 *
	 * Arguments are split with the command's known arity. Quoted strings and
	 * escaped commas follow rtorrent's parser, while the final argument keeps
	 * raw commas for compatibility with labels and directories such as
	 * "Movies, Inc". A value the client already quoted is unquoted here, then
	 * re-quoted, rather than dropped: cross-seed and others send
	 * d.custom1.set="label".
	 */
	private static function rebuildSafeLoadParam($paramValue, $safeParams, $directory = null, $version = null)
	{
		$separator = strpos($paramValue, '=');
		if($separator === false)
			return null;

		$command = self::rawCommandName($paramValue);
		// A nested global setter would bypass the direct call's recovery floor.
		if($command === 'network.xmlrpc.size_limit.set' || self::isDeniedCommand($command))
			return null;
		if(!in_array($command, $safeParams, true)
			|| !self::nativeOnDaemon($command, $version))
			return null;

		$maxArguments = isset(self::$multiArgCommands[$command])
			? self::$multiArgCommands[$command] : 1;
		$parts = self::splitLoadArguments(substr($paramValue, $separator + 1), $maxArguments);
		if($parts === null)
			return null;

		// Both shipped endpoints provide boundary options. Any directory setter
		// outside the configured boundary returns false here and makes the
		// outer request locally terminal with no transport call.
		if(($directory !== null) && in_array($command, self::$directoryCommands, true))
		{
			$path = isset($parts[0]) ? $parts[0] : '';
			// Quoted whitespace is path data. Do not validate trimmed bytes
			// and forward a different, possibly relative path to the daemon.
			// Dot segments are also unsafe: the kernel resolves them after a
			// symlink, while lexical normalization would collapse them first.
			if($path !== trim($path) || in_array('.', explode('/', $path), true)
				|| in_array('..', explode('/', $path), true) || !self::directoryIsAllowed($path, $directory))
				return false;
		}

		$arguments = array();
		foreach($parts as $argument)
		{
			// An argument whose first character is '$' is parsed and called as a
			// command after quoting is undone, so quoting cannot make it safe.
			// Unquoted values are already trimmed by the split; trimming again
			// here would not turn a leading space into a leading '$'.
			if(isset($argument[0]) && $argument[0] === '$')
				return null;

			$arguments[] = '"'.str_replace(array('\\', '"'), array('\\\\', '\\"'), $argument).'"';
		}

		return $command.'='.implode(',', $arguments);
	}

}
